app/User/__init__.py
from flask import Blueprint

UserModule = Blueprint('User',
                           __name__,
                           static_folder='static',
                           url_prefix='/user',
                           template_folder='templates'
                           )
from . import views

app/User/views.py
from . import UserModule
from flask_login import current_user, login_required
from flask import render_template
from app.Engine.DB.db_api import UserApi, GameApi


@UserModule.route('/<user_id>', methods=['GET', 'POST'])
@UserModule.route('', methods=['GET', 'POST'])
@login_required
def user_main(user_id=None):
    if user_id is None:
        user_id = current_user.id
    else:
        user_id = int(user_id)
    achievements = None
    classic_creations = None
    classic_games = None

    user_api = UserApi()
    user = user_api.get_user_for_user_id(user_id)
    if user:
        game_api = GameApi()
        achievements = user_api.get_user_achievements()
        my_finished_games = [game for game in game_api.list_games('my_games', user) if game.status.name == 'finished']
        classic_games = [game for game in my_finished_games if game.game_type.name == 'classic']
        classic_creations = []
        for g in classic_games:
            game_api.game = g
            classic_creations.append(game_api.get_player_object_for_user_id(user_id))

    return render_template('User_index.html',
                           user=user,
                           achievements=achievements,
                           classic_creations=classic_creations)


@UserModule.route('/list', methods=['GET', 'POST'])
@UserModule.route('/list/<page>', methods=['GET', 'POST'])
@login_required
def user_list(page=1):
    page = int(page)
    user_api = UserApi()
    users = user_api.get_all_users(page, 10)

    return render_template('User_list.html',
                           users=users)


@UserModule.route('/toplist', methods=['GET', 'POST'])
@UserModule.route('/toplist/<page>', methods=['GET', 'POST'])
@login_required
def user_toplist(page=1):
    page = int(page)
    game_api = GameApi()
    game_players = game_api.get_game_players()
    users = extract_users_data_from_db_game_players(game_players)
    users = add_calculated_users_data(users)
    users = {k: v for k, v in sorted(users.items(), key=lambda item: item[1]['OM_points'], reverse=True)}

    return render_template('User_toplist.html',
                           users=users)


def add_calculated_users_data(users):
    for user in users:
        users[user]['won_percentage'] = round(users[user]['games_won'] / users[user]['games_played'] * 100, 2)
        users[user]['OM_points'] = users[user]['games_played'] + users[user]['games_won'] * 2 + users[user]['games_mvp'] * 7
    return users


def extract_users_data_from_db_game_players(game_players):
    users = {}
    for gp in game_players:
        if gp.status != 'special':
            if gp.user_id not in users:
                users[gp.user_id] = {}

            if 'games_played' not in users[gp.user_id]:
                users[gp.user_id]['games_played'] = 1
            else:
                users[gp.user_id]['games_played'] += 1

            won = int(gp.winner)
            if 'games_won' not in users[gp.user_id]:
                users[gp.user_id]['games_won'] = won
            else:
                users[gp.user_id]['games_won'] += won

            mvp = 'mvp' in [a.achievement.name for a in gp.achievements]
            if mvp:
                mvp = 1
            else:
                mvp = 0
            if 'games_mvp' not in users[gp.user_id]:
                users[gp.user_id]['games_mvp'] = mvp
            else:
                users[gp.user_id]['games_mvp'] += mvp

            users[gp.user_id]['user_name'] = gp.user.name

    return users

app/User/templates/User_index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('User.static', filename='css/styles.css') }}">
{% endblock %}

{% block scripts %}
{{ super() }}
{%endblock%}

{%block title%}OpenMafia - użytkownicy{%endblock%}
{%block main_content%}

<div class="tabs">
  <div class="tab-content">
    <div id="general" class="active">
      <div class="content-box">
        <b>{{ user.name }}</b>
      </div>
      <div class="content-box">
          Osiągnięcia<br/>
        {% for a in achievements %}
        {% if a.player_id == None %}
        <div title="{{ a.achievement.description }}">
          <img src="{{url_for('static', filename='images/awards/'+a.achievement.name+'.png')}}"/>
        </div>
        {% endif %}
        {% endfor %}
      </div>
      <div class="content-box">
        <b>Kreacje klasyczne</b><br />
        <div class="posts-container">
          {% for creation in classic_creations %}
          <div class="post">
            <div class="post-header">
              <span class="post-login">{{ creation.name }}</span>
              <a href="{{url_for('SetupGameModule.lobby', game_id=creation.game.id)}}"><span class="post-date">{{ creation.game.name }}</span></a>
              <span class="post-roles">
                {% for role in creation.roles %}
                {{ role.role.visible_name }}
                {% if loop.index < creation.roles|length %}, {% endif %}
                {% endfor %}
              </span>
            </div>
            <div class="post-content">
              <p>
                {% for a in achievements %}
                {% if a.player_id == creation.id %}
                <div title="{{ a.achievement.visible_name }} - {{ a.achievement.description }}">
                  <img class="post-achievement" src="{{url_for('static', filename='images/awards/'+a.achievement.name+'.png')}}"/>
                </div>
                {% endif %}
                {% endfor %}
              </p>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

{%endblock%}

app/User/templates/User_list.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('User.static', filename='css/styles.css') }}">
{% endblock %}
{% macro render_pagination(pagination) %}
  <div class=page-items>
    {{ pagination.first }} - {{ pagination.last }} of {{ pagination.total }}
  </div>
  <div class=pagination>
    {% for page in pagination.iter_pages() %}
      {% if page %}
        {% if page != pagination.page %}
          <a href='{{url_for("User.user_list", page=page)}}'>{{ page }}</a>
        {% else %}
          <strong>{{ page }}</strong>
        {% endif %}
      {% else %}
        <span class=ellipsis>…</span>
      {% endif %}
    {% endfor %}
  </div>
{% endmacro %}
{% block scripts %}
{{ super() }}
{%endblock%}

{%block title%}OpenMafia - użytkownicy{%endblock%}
{%block main_content%}

<div class="tabs">
  <div class="tab-content">
    <div id="general" class="active">
      <div class="content-box">

        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">User</th>
            </tr>
          </thead>
          <tbody>
          {% for user in users.items %}
            <tr>
             <th scope="row">{{ user.id }}</th>
                <td><a href="{{url_for('User.user_main', user_id=user.id)}}">{{ user.name }}</a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
        {{ render_pagination(users) }}

      </div>
    </div>
  </div>
</div>

{%endblock%}

app/User/templates/User_toplist.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block styles %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('User.static', filename='css/styles.css') }}">
{% endblock %}

{% block scripts %}
{{ super() }}
{%endblock%}

{%block title%}OpenMafia - użytkownicy{%endblock%}
{%block main_content%}

<div class="tabs">
  <div class="tab-content">
    <div id="general" class="active">
      <div class="content-box">

        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">User</th>
              <th scope="col">MVP</th>
              <th scope="col">Wygranych</th>
              <th scope="col">Wszystkich gier</th>
              <th scope="col">% wygranych</th>
              <th scope="col">Punkty</th>
            </tr>
          </thead>
          <tbody>
          {% for user in users %}
            <tr>
             <th scope="row">{{ users[user].id }}</th>
                <td><a href="{{url_for('User.user_main', user_id=user)}}">{{ users[user]['user_name'] }}</a></td>
                <td>{{ users[user]['games_mvp'] }}</td>
                <td>{{ users[user]['games_won'] }}</td>
                <td>{{ users[user]['games_played'] }}</td>
                <td>{{ users[user]['won_percentage'] }}</td>
                <td title="MVP=10p, wygrana=3p, przegrana=1p">{{ users[user]['OM_points'] }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

{%endblock%}